export enum Text {
  HI_AGAINE = 'Привіт знову',
  HI_ADMIN = 'Привіт ви АДМІН',
  YOU_ARE_SUCCESSFULLY_REGISTERED = 'ви успішно зареєстровані в системі ✅',
  YOUR_ORDER_CANCELED = 'Ваш запис відмінено, приходьте ще 🌟',
  ENTER_CAR_BRAND = 'Оберіть тип масажу 💆‍♂️',
  ENTER_CAR_NUMBER = 'Оберіть тривалість сеансу ⏱️',
  ENTER_ADDITIONAL_SERVICE = 'Оберіть додаткові послуги 🌿',
  CHOOSE_DAY = 'Введіть день запису 📅 в форматі: DD.MM.YYYY',
  CHOOSE_PART_OF_DAY = `
    Оберіть час 🕙 `,
  ORDER_CREATED = "Ви записані ✅\nЗ вами зв'яжуться в обрану дату 📞",
  SOMETHING_WENT_WRONG = 'Щось пішло не так, зверніться, будь ласка, до адміністрації ❌',
  ORDER_REMOVED = 'Запис видалено ✅',
  NEW_ORDER = 'Новий запис 📝',
  CAR_BRAND = 'Тип масажу',
  CAR_NUMBER = 'Тривалість сеансу',
  DELETE = 'Видалити',
  USER_WAS_DELETED = '⛔️ Користувач був видалений з бази\n(не тількищо, мабуть давно 🤷🏼‍♂️)',
  NAME = "Ім'я",
  NUMBER = 'Номер',
  TG = 'Telegram',
  CAR = 'Послуга',
  DATE = 'Дата',
  PART_OF_DAY = 'Частина дня',
  TODAY = 'Сьогодні',
  TOMORROW = 'Завтра',
  ALL_ORDERS_TO = 'Всі записи до',
  MORNING = 'з 9:00 до 13:00 ☀️',
  AFTERNOON = 'з 13:00 до 18:00 🌆',
  ORDERS = 'Записи',
}
